version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: shakespeare:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload